script <- sub("^--file=", "", grep("^--file=", commandArgs(), value = TRUE))
root <- dirname(dirname(normalizePath(script)))
setwd(root)
Sys.setenv(RENV_PROJECT = root)
source("renv/activate.R")
for (file in list.files("R", pattern = "[.]R$", full.names = TRUE)) source(file)
plot_results(load_results(), "figs")
